# APPLYING THE XGBOOST ALGORITHM ON TRAINING DATASET AND GENERATING SUBMISSION FILE

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.cross_validation import  cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.linear_model import ElasticNet, Lasso,  BayesianRidge, LassoLarsIC
from sklearn.ensemble import RandomForestRegressor,  GradientBoostingRegressor
from sklearn.kernel_ridge import KernelRidge
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error
import xgboost as xgb

C:\Users\HarShreya\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
df=pd.read_csv('training_5.csv')

In [38]:
df.head()

pid  bucket  city  ref_type  ref_name  ref_source
0  400061       3     3         1        77           4
1   25535       0     0         1       136           5
2  409013       3    21         1        91           5
3  164585       2    11         1       150           0
4   56960       2     3         1       150           9

In [37]:
df.drop(labels=['age','gender','s/c','service'],axis=1,inplace=True)

In [39]:
Y= df.bucket

X= df.drop(labels=['bucket'],axis = 1)

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3)

In [41]:
model_xgb=xgb.XGBClassifier(colsample_bytree=0.4603, gamma=0.0468, 
                             learning_rate=0.05, max_depth=3, 
                             min_child_weight=1.7817, n_estimators=2200,
                             reg_alpha=0.4640, reg_lambda=0.8571,
                             subsample=0.5213, silent=1,
                             random_state =7, nthread = -1)

In [42]:
model_xgb.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.4603, gamma=0.0468, learning_rate=0.05,
       max_delta_step=0, max_depth=3, min_child_weight=1.7817,
       missing=None, n_estimators=2200, n_jobs=1, nthread=-1,
       objective='multi:softprob', random_state=7, reg_alpha=0.464,
       reg_lambda=0.8571, scale_pos_weight=1, seed=None, silent=1,
       subsample=0.5213)

In [43]:
predictions=model_xgb.predict(X_test)

C:\Users\HarShreya\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [14]:
predictions

array([3, 3, 2, ..., 2, 2, 2], dtype=int64)

In [18]:
from sklearn.cross_validation import  cross_val_score
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [19]:
print(confusion_matrix(y_test,predictions))

[[ 516  184   67  216]
 [ 105  544  336  522]
 [  12   48 5728  791]
 [  25  154 2212 2835]]


In [44]:
print(accuracy_score(y_test,predictions)*100)

48.83525708289611


In [47]:
df1=pd.read_csv('training_ready.csv')

In [48]:
predictions=model_xgb.predict(df1)

C:\Users\HarShreya\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [50]:
type(predictions)

numpy.ndarray

In [51]:
pred=pd.Series(predictions)

In [56]:
sol=[]
for i in predictions:
    if i==0:
        sol.append('High')
    elif i==1:
        sol.append('High-Med')
    elif i==2:
        sol.append('Low')
    else:
        sol.append('Med')
  

In [58]:
ans=pd.DataFrame(data=sol,columns=['Bucket'])

In [59]:
ans.to_csv('first_submission.csv',index=False)